/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter eslint_disable,server_grpc1
// @generated from protobuf file "workloadapi.proto" (syntax proto3)
// tslint:disable
import { ValidateJWTSVIDResponse } from "./workloadapi";
import { ValidateJWTSVIDRequest } from "./workloadapi";
import { JWTBundlesResponse } from "./workloadapi";
import { JWTBundlesRequest } from "./workloadapi";
import { JWTSVIDResponse } from "./workloadapi";
import { JWTSVIDRequest } from "./workloadapi";
import { X509BundlesResponse } from "./workloadapi";
import { X509BundlesRequest } from "./workloadapi";
import { X509SVIDResponse } from "./workloadapi";
import { X509SVIDRequest } from "./workloadapi";
import type * as grpc from "@grpc/grpc-js";
/**
 * ///////////////////////////////////////////////////////////////////////
 * X509-SVID Profile
 * ///////////////////////////////////////////////////////////////////////
 *
 * @generated from protobuf service SpiffeWorkloadAPI
 */
export interface ISpiffeWorkloadAPI extends grpc.UntypedServiceImplementation {
    /**
     * Fetch X.509-SVIDs for all SPIFFE identities the workload is entitled to,
     * as well as related information like trust bundles and CRLs. As this
     * information changes, subsequent messages will be streamed from the
     * server.
     *
     * @generated from protobuf rpc: FetchX509SVID
     */
    fetchX509SVID: grpc.handleServerStreamingCall<X509SVIDRequest, X509SVIDResponse>;
    /**
     * Fetch trust bundles and CRLs. Useful for clients that only need to
     * validate SVIDs without obtaining an SVID for themself. As this
     * information changes, subsequent messages will be streamed from the
     * server.
     *
     * @generated from protobuf rpc: FetchX509Bundles
     */
    fetchX509Bundles: grpc.handleServerStreamingCall<X509BundlesRequest, X509BundlesResponse>;
    // ///////////////////////////////////////////////////////////////////////
    // JWT-SVID Profile
    // ///////////////////////////////////////////////////////////////////////

    /**
     * Fetch JWT-SVIDs for all SPIFFE identities the workload is entitled to,
     * for the requested audience. If an optional SPIFFE ID is requested, only
     * the JWT-SVID for that SPIFFE ID is returned.
     *
     * @generated from protobuf rpc: FetchJWTSVID
     */
    fetchJWTSVID: grpc.handleUnaryCall<JWTSVIDRequest, JWTSVIDResponse>;
    /**
     * Fetches the JWT bundles, formatted as JWKS documents, keyed by the
     * SPIFFE ID of the trust domain. As this information changes, subsequent
     * messages will be streamed from the server.
     *
     * @generated from protobuf rpc: FetchJWTBundles
     */
    fetchJWTBundles: grpc.handleServerStreamingCall<JWTBundlesRequest, JWTBundlesResponse>;
    /**
     * Validates a JWT-SVID against the requested audience. Returns the SPIFFE
     * ID of the JWT-SVID and JWT claims.
     *
     * @generated from protobuf rpc: ValidateJWTSVID
     */
    validateJWTSVID: grpc.handleUnaryCall<ValidateJWTSVIDRequest, ValidateJWTSVIDResponse>;
}
/**
 * @grpc/grpc-js definition for the protobuf service SpiffeWorkloadAPI.
 *
 * Usage: Implement the interface ISpiffeWorkloadAPI and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: ISpiffeWorkloadAPI = ...
 * server.addService(spiffeWorkloadAPIDefinition, service);
 * ```
 */
export const spiffeWorkloadAPIDefinition: grpc.ServiceDefinition<ISpiffeWorkloadAPI> = {
    fetchX509SVID: {
        path: "/SpiffeWorkloadAPI/FetchX509SVID",
        originalName: "FetchX509SVID",
        requestStream: false,
        responseStream: true,
        responseDeserialize: bytes => X509SVIDResponse.fromBinary(bytes),
        requestDeserialize: bytes => X509SVIDRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(X509SVIDResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(X509SVIDRequest.toBinary(value))
    },
    fetchX509Bundles: {
        path: "/SpiffeWorkloadAPI/FetchX509Bundles",
        originalName: "FetchX509Bundles",
        requestStream: false,
        responseStream: true,
        responseDeserialize: bytes => X509BundlesResponse.fromBinary(bytes),
        requestDeserialize: bytes => X509BundlesRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(X509BundlesResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(X509BundlesRequest.toBinary(value))
    },
    fetchJWTSVID: {
        path: "/SpiffeWorkloadAPI/FetchJWTSVID",
        originalName: "FetchJWTSVID",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => JWTSVIDResponse.fromBinary(bytes),
        requestDeserialize: bytes => JWTSVIDRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(JWTSVIDResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(JWTSVIDRequest.toBinary(value))
    },
    fetchJWTBundles: {
        path: "/SpiffeWorkloadAPI/FetchJWTBundles",
        originalName: "FetchJWTBundles",
        requestStream: false,
        responseStream: true,
        responseDeserialize: bytes => JWTBundlesResponse.fromBinary(bytes),
        requestDeserialize: bytes => JWTBundlesRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(JWTBundlesResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(JWTBundlesRequest.toBinary(value))
    },
    validateJWTSVID: {
        path: "/SpiffeWorkloadAPI/ValidateJWTSVID",
        originalName: "ValidateJWTSVID",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => ValidateJWTSVIDResponse.fromBinary(bytes),
        requestDeserialize: bytes => ValidateJWTSVIDRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ValidateJWTSVIDResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ValidateJWTSVIDRequest.toBinary(value))
    }
};
